version: "3.3"

services:

  portainer:
    image: portainer/portainer
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: portainer
        target: /data
    networks:
      - proxy
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.docker.network=proxy
        - traefik.frontend.rule=Host:portainer.kombinat.lan
        - traefik.enable=true
        - traefik.port=9000
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
  
  docker-proxy:
    image: rancher/socat-docker
    networks:
      - proxy
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  traefik:
    image: traefik:1.5
    depends_on:
      - docker-proxy
      - marathon
      - zetcd
      - chronos
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    command: 
      - --loglevel=debug
      - --docker
      - --docker.swarmmode
      - --docker.domain=kombinat.lan
      - --docker.endpoint=tcp://docker-proxy:2375
      - --marathon
      - --marathon.endpoint=http://marathon:8080
      - --marathon.domain=kombinat.lan
      - --web
      - --web.address=:8080
      - --defaultentrypoints=http
      - --entrypoints=Name:http Address::80
    networks:
      - proxy
      - mesos
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        window: 120s

  zetcd:
    image: quay.io/coreos/zetcd
    command: ["--endpoints", "172.17.8.2:2379", "--logtostderr", "-v", "9"]
    networks:
      - mesos
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

  master:
    image: axelspringer/mesos-master:1.4.1
    depends_on:
      - zetcd
    networks:
      - mesos
    environment:
      - MESOS_CLUSTER=kombinat
      - MESOS_PORT=5050
      - MESOS_ZK=zk://zetcd:2181/mesos
#     - MESOS_ADVERTISE_IP=MASTER_IP
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=replicated_log
    labels:
      com.mesos: "master"
    deploy:
      mode: global
      labels:
        - traefik.docker.network=mesos
        - traefik.frontend.rule=Host:master.kombinat.lan
        - traefik.enable=true
        - traefik.port=5050
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

  agent:
    image: axelspringer/mesos-agent:1.4.1
    user: root
    networks:
      - mesos
    depends_on:
      - zetcd
      - master
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://zetcd:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_WORK_DIR=/var/lib/mesos/agent
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

  marathon:
    image: axelspringer/marathon:1.5.2
    command:
      - --master=zk://zetcd:2181/mesos
      - --zk=zk://zetcd:2181/marathon
      - --webui_url=http://marathon.kombinat.lan
      - --default_network_name=mesos
      - --enable_features=vips,task_killing
    depends_on:
      - zetcd
      - master
      - agent
    networks:
      - mesos
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - traefik.docker.network=mesos
        - traefik.frontend.rule=Host:marathon.kombinat.lan
        - traefik.enable=true
        - traefik.port=8080
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
  
  chronos:
    image: axelspringer/chronos:3.0.2
    command:
      - --master=zk://zetcd:2181/mesos
      - --zk_hosts=zetcd:2181
      - --zk_path=/chronos
      - --webui_url=https://chronos.kombinat.lan
      - --http_compression
      - --http_port=8080
    depends_on:
      - zetcd
      - master
      - agent
    networks:
      - mesos
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - traefik.docker.network=mesos
        - traefik.frontend.rule=Host:chronos.kombinat.lan
        - traefik.enable=true
        - traefik.port=8080
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

volumes:
  portainer:

networks:
  proxy:
    external: true

  mesos:
    external: true
