version: "3.2"

services:
  
  # watchtower:
  #   image: centurylink/watchtower
  #   command: --cleanup
  #   volumes:
  #     - type: bind
  #       source: /run/docker.sock
  #       target: /var/run/docker.sock
  #   deploy:
  #     mode: global
  #     restart_policy:
  #       condition: on-failure
  #       delay: 30s
  #       max_attempts: 5
  #       window: 120s
  
  exhibitor:
    image: pixelmilk/exhibitor:1.6.0-3.4.10
    environment:
      - LOCAL_IPV4=true
    user: root
    networks:
      - mesos
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
        mode: host
    labels:
      com.mesos: "exhibitor"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s

  master:
    image: pixelmilk/mesos-master:1.3.1
    networks:
      - mesos
    ports:
      - target: 5050
        published: 5050
        protocol: tcp
        mode: host
    environment:
      - MESOS_PORT=5050
      - MESOS_ZK=zk://exhibitor:2181/mesos
#     - MESOS_ADVERTISE_IP=MASTER_IP
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
    labels:
      com.mesos: "master"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s

  agent:
    image: pixelmilk/mesos-agent:1.3.1
    user: root
    networks:
      - mesos
    depends_on:
      - exhibitor
      - master
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/docker.sock:/var/run/docker.sock:rw
    tmpfs:
      - /run:rw,exec,nosuid,size=2097152k
      - /tmp:rw,exec,nosuid,size=2097152k
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://exhibitor:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_WORK_DIR=/var/lib/mesos/agent
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
  
  # dns:
  #   image: mesosphere/mesos-dns:0.5.2

  marathon:
    image: pixelmilk/marathon:1.4.7
    command: --master zk://exhibitor:2181/mesos --zk zk://exhibitor:2181/marathon
    depends_on:
      - agent
    networks:
      - mesos
      - proxy
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s

  traefik:
    image: traefik
    command: --marathon --marathon.endpoint="http://marathon:8080" --web.address=":8383"
    networks:
      - mesos
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8383:8383
      - 8484:8484
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s

networks:
  mesos:
    driver: overlay
    driver_opts:
      encrypted: ""
  
  proxy:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: ""